/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.ServiceController;
import entities.ServiceEntity;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Vinicius
 */
public class CreateService extends javax.swing.JPanel {

    /**
     * Creates new form CreateService1
     */
    public CreateService() {
        initComponents();
        ServiceController controller = new ServiceController();
        controller.getAllServices(this.jTableServices);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNameService = new javax.swing.JLabel();
        jLabelRate = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextAreaDescription = new javax.swing.JTextArea();
        jLabel3 = new javax.swing.JLabel();
        jTextFieldNameService = new javax.swing.JTextField();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTableServices = new javax.swing.JTable();
        jButtonAdd = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jFormattedTextFieldRate = new javax.swing.JFormattedTextField();
        jButtonModify = new javax.swing.JButton();
        jButtonDelete = new javax.swing.JButton();
        jButtonUndo = new javax.swing.JButton();

        jLabelNameService.setText("Nome do Serviço:");

        jLabelRate.setText("Taxa:");

        jTextAreaDescription.setColumns(20);
        jTextAreaDescription.setRows(5);
        jScrollPane1.setViewportView(jTextAreaDescription);

        jLabel3.setText("Descrição:");

        jTableServices.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Nome Serviço", "Taxa", "Descrição"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTableServices.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTableServicesMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jTableServices);
        if (jTableServices.getColumnModel().getColumnCount() > 0) {
            jTableServices.getColumnModel().getColumn(1).setResizable(false);
            jTableServices.getColumnModel().getColumn(2).setResizable(false);
        }

        jButtonAdd.setText("Adicionar");
        jButtonAdd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonAddActionPerformed(evt);
            }
        });

        jButtonClear.setText("Limpar");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jFormattedTextFieldRate.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("R$ #,##0.00"))));
        jFormattedTextFieldRate.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusGained(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldRateFocusGained(evt);
            }
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldRateFocusLost(evt);
            }
        });

        jButtonModify.setVisible(false);
        jButtonModify.setText("Modificar");
        jButtonModify.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonModifyActionPerformed(evt);
            }
        });

        jButtonDelete.setVisible(false);
        jButtonDelete.setText("Excluir");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jButtonUndo.setVisible(false);
        jButtonUndo.setText("UNDO");
        jButtonUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUndoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNameService)
                                .addGap(18, 18, 18)
                                .addComponent(jTextFieldNameService, javax.swing.GroupLayout.PREFERRED_SIZE, 166, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                                .addGap(42, 42, 42)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel3)
                                    .addComponent(jLabelRate))
                                .addGap(18, 18, 18)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(jScrollPane1)
                                    .addComponent(jFormattedTextFieldRate))))
                        .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonClear)
                                .addComponent(jButtonModify))
                            .addGap(18, 18, 18)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jButtonAdd)
                                .addComponent(jButtonDelete, javax.swing.GroupLayout.PREFERRED_SIZE, 77, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(jButtonUndo))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 466, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(39, 39, 39)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelNameService)
                            .addComponent(jTextFieldNameService, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabelRate)
                            .addComponent(jFormattedTextFieldRate, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(18, 18, 18)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel3))
                        .addGap(24, 24, 24)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonAdd)
                            .addComponent(jButtonClear))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jButtonModify)
                            .addComponent(jButtonDelete))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonUndo))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 475, Short.MAX_VALUE))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jButtonAddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonAddActionPerformed
        // TODO add your handling code here:

        String rateString = this.jFormattedTextFieldRate.getText();
        if (!rateString.isEmpty()) {
            rateString = rateString.substring(2)
                    .replace(",", ".");
        } else {
            JOptionPane.showMessageDialog(null, "Por Favor, preencha todos os campos", "Vazio!", JOptionPane.ERROR_MESSAGE);
            return;
        }
        ServiceEntity newService = new ServiceEntity(
                this.jTextFieldNameService.getText(),
                Double.parseDouble(rateString),
                this.jTextAreaDescription.getText()
        );
        ServiceController controller = new ServiceController();

        if (!controller.createService(newService)) {
            JOptionPane.showMessageDialog(null, "Por Favor, preencha todos os campos", "Vazio!", JOptionPane.ERROR_MESSAGE);
        } else {
            controller.addListService(newService, this.jTableServices);
            clear();
        }
    }//GEN-LAST:event_jButtonAddActionPerformed

    private void jFormattedTextFieldRateFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldRateFocusLost
        // TODO add your handling code here:
        String value = this.jFormattedTextFieldRate.getText();
        this.jFormattedTextFieldRate.setText("R$ " + value);
    }//GEN-LAST:event_jFormattedTextFieldRateFocusLost

    private void jFormattedTextFieldRateFocusGained(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldRateFocusGained
        // TODO add your handling code here:
        this.jFormattedTextFieldRate.setText("");
    }//GEN-LAST:event_jFormattedTextFieldRateFocusGained

    private void jTableServicesMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTableServicesMouseClicked
        // TODO add your handling code here:
        int row = this.jTableServices.getSelectedRow();

        String name = this.jTableServices.getValueAt(row, 0).toString();
        String rate = this.jTableServices.getValueAt(row, 1).toString();
        String description = this.jTableServices.getValueAt(row, 2).toString();

        this.jTextFieldNameService.setText(name);
        this.jTextAreaDescription.setText(description);
        this.jFormattedTextFieldRate.setText("R$ " + rate);
        this.jButtonAdd.setVisible(false);
        this.jButtonModify.setVisible(true);
        this.jButtonDelete.setVisible(true);
    }//GEN-LAST:event_jTableServicesMouseClicked

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:     
        clear();

    }//GEN-LAST:event_jButtonClearActionPerformed

    private void clear() {
        this.jTextFieldNameService.setText("");
        this.jTextAreaDescription.setText("");
        this.jFormattedTextFieldRate.setText("");
        this.jButtonAdd.setVisible(true);
        this.jButtonModify.setVisible(false);
        this.jButtonDelete.setVisible(false);
        this.jTableServices.clearSelection();
    }

    private void jButtonModifyActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonModifyActionPerformed
        // TODO add your handling code here:
        int row = this.jTableServices.getSelectedRow();

        String name = this.jTableServices.getValueAt(row, 0).toString();
        String rate = this.jTableServices.getValueAt(row, 1).toString().replace(",", ".");
        String description = this.jTableServices.getValueAt(row, 2).toString();

        String rateString = this.jFormattedTextFieldRate.getText();
        if (!rateString.isEmpty()) {
            rateString = rateString.substring(2)
                    .replace(",", ".");
        } else {
            JOptionPane.showMessageDialog(null, "Por Favor, preencha todos os campos", "Vazio!", JOptionPane.ERROR_MESSAGE);
            return;
        }

        ServiceEntity newService = new ServiceEntity(
                this.jTextFieldNameService.getText(),
                Double.parseDouble(rateString),
                this.jTextAreaDescription.getText()
        );

        ServiceEntity oldService = new ServiceEntity(
                name,
                Double.parseDouble(rate),
                description
        );

        ServiceController controller = new ServiceController();

        if (!controller.updateService(oldService, newService, this.jTableServices)) {
            JOptionPane.showMessageDialog(null, "Por Favor, preencha todos os campos", "Vazio!", JOptionPane.ERROR_MESSAGE);
        } else {
            clear();
        }


    }//GEN-LAST:event_jButtonModifyActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        int row = this.jTableServices.getSelectedRow();
        String name = this.jTableServices.getValueAt(row, 0).toString();
        String rate = this.jTableServices.getValueAt(row, 1).toString().replace(",", ".");
        String description = this.jTableServices.getValueAt(row, 2).toString();

        ServiceEntity service = new ServiceEntity(
                name,
                Double.parseDouble(rate),
                description
        );

        ServiceController controller = new ServiceController();
        controller.deleteService(service, this.jTableServices);
        clear();
        this.jButtonUndo.setVisible(true);
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUndoActionPerformed
        // TODO add your handling code here:
        ServiceController controller = new ServiceController();
        controller.undo();
        this.jButtonUndo.setVisible(false);        
        DefaultTableModel df = (DefaultTableModel) this.jTableServices.getModel();
        df.getDataVector().removeAllElements();
        controller.getAllServices(this.jTableServices);
    }//GEN-LAST:event_jButtonUndoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonAdd;
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonModify;
    private javax.swing.JButton jButtonUndo;
    private javax.swing.JFormattedTextField jFormattedTextFieldRate;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabelNameService;
    private javax.swing.JLabel jLabelRate;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable jTableServices;
    private javax.swing.JTextArea jTextAreaDescription;
    private javax.swing.JTextField jTextFieldNameService;
    // End of variables declaration//GEN-END:variables
}
