/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package views;

import controllers.EmployeeController;
import entities.AddressEntity;
import entities.CommissionedEntity;
import entities.EmployeeEntity;
import entities.HourlyEntity;
import entities.SalariedEntity;
import java.awt.Dimension;
import javax.swing.JOptionPane;
import utils.TypeEmployEnum;

/**
 *
 * @author Vinicius
 */
public class CreateEmployee extends javax.swing.JPanel {

    /**
     * Creates new form AdicionarEmpregado
     */
    private boolean updateMode;

    public CreateEmployee() {
        updateMode = false;
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabelNome = new javax.swing.JLabel();
        jLabelCEP = new javax.swing.JLabel();
        jLabelTipo = new javax.swing.JLabel();
        jLabelLogradouro = new javax.swing.JLabel();
        jLabelNumero = new javax.swing.JLabel();
        jLabelBairro = new javax.swing.JLabel();
        jLabelCidade = new javax.swing.JLabel();
        jLabelHoraTrabalho = new javax.swing.JLabel();
        jLabelSalario = new javax.swing.JLabel();
        jLabelComissao = new javax.swing.JLabel();
        jComboBoxTipo = new javax.swing.JComboBox<>();
        jButtonSalvar = new javax.swing.JButton();
        jButtonClear = new javax.swing.JButton();
        jTextFieldName = new javax.swing.JTextField();
        jFormattedTextFieldCEP = new javax.swing.JFormattedTextField();
        jTextFieldBairro = new javax.swing.JTextField();
        jTextFieldCidade = new javax.swing.JTextField();
        jTextFieldLogradouro = new javax.swing.JTextField();
        jTextFieldNumero = new javax.swing.JTextField();
        jFormattedTextFieldHoraTrabalho = new javax.swing.JFormattedTextField();
        jFormattedTextFieldSalario = new javax.swing.JFormattedTextField();
        jFormattedTextFieldComissao = new javax.swing.JFormattedTextField();
        jButtonDelete = new javax.swing.JButton();
        jLabelCPF = new javax.swing.JLabel();
        jTextFieldCPF = new javax.swing.JTextField();
        jButtonUndo = new javax.swing.JButton();

        setPreferredSize(new java.awt.Dimension(958, 589));

        jLabelNome.setText("Nome:");

        jLabelCEP.setText("CEP:");

        jLabelTipo.setText("Tipo:");

        jLabelLogradouro.setText("Rua/Avenida:");

        jLabelNumero.setText("N°");

        jLabelBairro.setText("Bairro:");

        jLabelCidade.setText("Cidade/UF:");

        jLabelHoraTrabalho.setVisible(false);
        jLabelHoraTrabalho.setText("Valor Hora");

        jLabelSalario.setVisible(false);
        jLabelSalario.setText("Salário:");

        jLabelComissao.setVisible(false);
        jLabelComissao.setText("Comissão:");

        jComboBoxTipo.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { TypeEmployEnum.Commissionaed.getType(), TypeEmployEnum.Salaried.getType(), TypeEmployEnum.Hourly.getType() }));
        jComboBoxTipo.setSelectedIndex(-1);
        jComboBoxTipo.addItemListener(new java.awt.event.ItemListener() {
            public void itemStateChanged(java.awt.event.ItemEvent evt) {
                jComboBoxTipoItemStateChanged(evt);
            }
        });
        jComboBoxTipo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBoxTipoActionPerformed(evt);
            }
        });

        jButtonSalvar.setText("Salvar");
        jButtonSalvar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonSalvarActionPerformed(evt);
            }
        });

        jButtonClear.setText("Limpar");
        jButtonClear.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonClearActionPerformed(evt);
            }
        });

        jTextFieldName.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N

        try {
            jFormattedTextFieldCEP.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.MaskFormatter("##.###-###")));
        } catch (java.text.ParseException ex) {
            ex.printStackTrace();
        }

        jFormattedTextFieldHoraTrabalho.setVisible(false);
        jFormattedTextFieldHoraTrabalho.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("R$ #,##0.00"))));
        jFormattedTextFieldHoraTrabalho.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldHoraTrabalhoFocusLost(evt);
            }
        });

        jFormattedTextFieldSalario.setVisible(false);
        jFormattedTextFieldSalario.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(new java.text.DecimalFormat("R$ #,##0.00"))));
        jFormattedTextFieldSalario.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldSalarioFocusLost(evt);
            }
        });

        jFormattedTextFieldComissao.setVisible(false);
        jFormattedTextFieldComissao.setFormatterFactory(new javax.swing.text.DefaultFormatterFactory(new javax.swing.text.NumberFormatter(java.text.NumberFormat.getPercentInstance())));
        jFormattedTextFieldComissao.addFocusListener(new java.awt.event.FocusAdapter() {
            public void focusLost(java.awt.event.FocusEvent evt) {
                jFormattedTextFieldComissaoFocusLost(evt);
            }
        });

        jButtonDelete.setVisible(false);
        jButtonDelete.setText("Deletar");
        jButtonDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonDeleteActionPerformed(evt);
            }
        });

        jLabelCPF.setText("CPF:");

        jButtonUndo.setText("Undo");
        jButtonUndo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButtonUndoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addContainerGap()
                        .addComponent(jButtonClear)
                        .addGap(36, 36, 36)
                        .addComponent(jButtonUndo, javax.swing.GroupLayout.PREFERRED_SIZE, 81, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButtonDelete)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jButtonSalvar)
                        .addGap(11, 11, 11))
                    .addGroup(javax.swing.GroupLayout.Alignment.LEADING, layout.createSequentialGroup()
                        .addGap(25, 25, 25)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelLogradouro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldLogradouro)
                                .addGap(10, 10, 10)
                                .addComponent(jLabelNumero)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 119, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelNome)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldName))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(jLabelCEP)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, 122, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jLabelBairro)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, 256, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(jLabelCidade)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(jTextFieldCidade, javax.swing.GroupLayout.DEFAULT_SIZE, 229, Short.MAX_VALUE)
                                .addGap(46, 46, 46))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                        .addGroup(layout.createSequentialGroup()
                                            .addComponent(jLabelTipo)
                                            .addGap(41, 41, 41)
                                            .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, 132, javax.swing.GroupLayout.PREFERRED_SIZE))
                                        .addGroup(layout.createSequentialGroup()
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jLabelSalario)
                                                .addComponent(jLabelHoraTrabalho)
                                                .addComponent(jLabelComissao))
                                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(jFormattedTextFieldComissao)
                                                .addComponent(jFormattedTextFieldSalario)
                                                .addComponent(jFormattedTextFieldHoraTrabalho))))
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabelCPF)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                        .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, 207, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 0, Short.MAX_VALUE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(32, 32, 32)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jLabelNome)
                    .addComponent(jTextFieldName, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCEP)
                    .addComponent(jLabelBairro)
                    .addComponent(jLabelCidade)
                    .addComponent(jFormattedTextFieldCEP, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldBairro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldCidade, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelLogradouro)
                    .addComponent(jLabelNumero, javax.swing.GroupLayout.PREFERRED_SIZE, 25, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldLogradouro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jTextFieldNumero, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(29, 29, 29)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelCPF)
                    .addComponent(jTextFieldCPF, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(47, 47, 47)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelTipo)
                    .addComponent(jComboBoxTipo, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelHoraTrabalho)
                    .addComponent(jFormattedTextFieldHoraTrabalho, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelSalario)
                    .addComponent(jFormattedTextFieldSalario, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabelComissao)
                    .addComponent(jFormattedTextFieldComissao, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 123, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButtonSalvar)
                    .addComponent(jButtonClear)
                    .addComponent(jButtonDelete)
                    .addComponent(jButtonUndo))
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void jComboBoxTipoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBoxTipoActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBoxTipoActionPerformed

    private void jFormattedTextFieldHoraTrabalhoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldHoraTrabalhoFocusLost
        // TODO add your handling code here:
        String value = this.jFormattedTextFieldHoraTrabalho.getText();
        this.jFormattedTextFieldHoraTrabalho.setText("R$ " + value);
    }//GEN-LAST:event_jFormattedTextFieldHoraTrabalhoFocusLost

    private void jFormattedTextFieldSalarioFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldSalarioFocusLost
        // TODO add your handling code here:
        String value = this.jFormattedTextFieldSalario.getText();
        this.jFormattedTextFieldSalario.setText("R$ " + value);
    }//GEN-LAST:event_jFormattedTextFieldSalarioFocusLost

    private void jFormattedTextFieldComissaoFocusLost(java.awt.event.FocusEvent evt) {//GEN-FIRST:event_jFormattedTextFieldComissaoFocusLost
        // TODO add your handling code here:
        String value = this.jFormattedTextFieldComissao.getText();
        this.jFormattedTextFieldComissao.setText(value + "%");
    }//GEN-LAST:event_jFormattedTextFieldComissaoFocusLost

    private void jButtonSalvarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonSalvarActionPerformed
        // TODO add your handling code here:
        
        EmployeeController controller = new EmployeeController();
        EmployeeEntity newEmployee = formatedAll();
        
        if (updateMode && !controller.updateEmployee(newEmployee)) {
            /*ModifyEmployee modifyEmployee = new ModifyEmployee();
            this.getRootPane().setContentPane(modifyEmployee);
            this.repaint();*/
            JOptionPane.showMessageDialog(null, "Por Favor, preencha todos os campos", "Vazio!", JOptionPane.ERROR);
        } else if (!updateMode && !controller.createEmployee(newEmployee)) {
            JOptionPane.showMessageDialog(null, "Por Favor, preencha todos os campos", "Vazio!", JOptionPane.ERROR);
        } else {
            clear();
        }
    }//GEN-LAST:event_jButtonSalvarActionPerformed

    private void jComboBoxTipoItemStateChanged(java.awt.event.ItemEvent evt) {//GEN-FIRST:event_jComboBoxTipoItemStateChanged
        // TODO add your handling code here:

        this.jLabelHoraTrabalho.setVisible(false);
        this.jLabelSalario.setVisible(false);
        this.jLabelComissao.setVisible(false);
        this.jFormattedTextFieldHoraTrabalho.setVisible(false);
        this.jFormattedTextFieldSalario.setVisible(false);
        this.jFormattedTextFieldComissao.setVisible(false);

        String typeEmployee = (String) this.jComboBoxTipo.getSelectedItem();
        if (TypeEmployEnum.Commissionaed.getType().equals(typeEmployee)) {

            this.jFormattedTextFieldComissao.setVisible(true);
            this.jFormattedTextFieldSalario.setVisible(true);
            this.jLabelComissao.setVisible(true);
            this.jLabelSalario.setVisible(true);
        } else if (TypeEmployEnum.Hourly.getType().equals(typeEmployee)) {
            this.jFormattedTextFieldHoraTrabalho.setVisible(true);
            this.jLabelHoraTrabalho.setVisible(true);
        } else if (TypeEmployEnum.Salaried.getType().equals(typeEmployee)) {
            this.jFormattedTextFieldSalario.setVisible(true);
            this.jLabelSalario.setVisible(true);
        }
    }//GEN-LAST:event_jComboBoxTipoItemStateChanged

    private void jButtonClearActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonClearActionPerformed
        // TODO add your handling code here:
        clear();
    }//GEN-LAST:event_jButtonClearActionPerformed

    private void jButtonDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonDeleteActionPerformed
        // TODO add your handling code here:
        EmployeeController controller = new EmployeeController();
        EmployeeEntity employeeEntity = formatedAll();
        controller.delete(employeeEntity);
        clear();
    }//GEN-LAST:event_jButtonDeleteActionPerformed

    private void jButtonUndoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButtonUndoActionPerformed
        // TODO add your handling code here:
        EmployeeController controller = new EmployeeController();
        controller.undo();
        this.jButtonUndo.setVisible(false);
    }//GEN-LAST:event_jButtonUndoActionPerformed

    private void clear() {
        updateMode = false;
        this.jButtonDelete.setVisible(false);
        this.jTextFieldCPF.setEditable(true);

        this.jLabelHoraTrabalho.setVisible(false);
        this.jLabelSalario.setVisible(false);
        this.jLabelComissao.setVisible(false);
        this.jFormattedTextFieldHoraTrabalho.setVisible(false);
        this.jFormattedTextFieldSalario.setVisible(false);
        this.jFormattedTextFieldComissao.setVisible(false);
        this.jComboBoxTipo.setSelectedIndex(-1);
        this.jTextFieldName.setText("");
        this.jFormattedTextFieldCEP.setText("");
        this.jTextFieldBairro.setText("");
        this.jTextFieldCidade.setText("");
        this.jTextFieldLogradouro.setText("");
        this.jTextFieldNumero.setText("");
        this.jTextFieldCPF.setText("");
    }

    public void updateMode(EmployeeEntity employee) {
        this.updateMode = true;

        this.jButtonDelete.setVisible(true);
        this.jTextFieldCPF.setEditable(false);

        if (employee instanceof CommissionedEntity) {
            CommissionedEntity commissionedEntity = (CommissionedEntity) employee;
            this.jLabelComissao.setVisible(true);
            this.jFormattedTextFieldComissao.setVisible(true);
            this.jFormattedTextFieldComissao.setText(commissionedEntity.getKickback());
            this.jComboBoxTipo.setSelectedIndex(0);

            this.jLabelSalario.setVisible(true);
            this.jFormattedTextFieldSalario.setVisible(true);
            this.jFormattedTextFieldSalario.setText(commissionedEntity.getSalary());

        } else if (employee instanceof HourlyEntity) {
            HourlyEntity hourlyEntity = (HourlyEntity) employee;
            this.jLabelSalario.setVisible(true);
            this.jFormattedTextFieldHoraTrabalho.setVisible(true);
            this.jFormattedTextFieldHoraTrabalho.setText(hourlyEntity.getWorkTime());
            this.jComboBoxTipo.setSelectedIndex(2);

        } else if (employee instanceof SalariedEntity) {
            SalariedEntity salariedEntity = (SalariedEntity) employee;
            this.jLabelSalario.setVisible(true);
            this.jFormattedTextFieldSalario.setVisible(true);
            this.jFormattedTextFieldSalario.setText(salariedEntity.getSalary());
            this.jComboBoxTipo.setSelectedIndex(1);

        }

        this.jTextFieldName.setText(employee.getName());
        this.jFormattedTextFieldCEP.setText(employee.getAddress().getCEP());
        this.jTextFieldBairro.setText(employee.getAddress().getDistrict());
        this.jTextFieldCidade.setText(employee.getAddress().getCity() + "/" + employee.getAddress().getStates());
        this.jTextFieldLogradouro.setText(employee.getAddress().getAddress());
        this.jTextFieldNumero.setText(employee.getAddress().getNumber());
        this.jTextFieldCPF.setText(employee.getCPF());

    }
    
    private EmployeeEntity formatedAll(){
        int barCity = this.jTextFieldCidade.getText().indexOf("/");
        AddressEntity addressEmployee = new AddressEntity(this.jTextFieldLogradouro.getText(),
                this.jTextFieldNumero.getText(),
                this.jTextFieldBairro.getText(),
                this.jTextFieldCidade.getText().substring(0, barCity - 1),
                this.jTextFieldCidade.getText().substring(barCity,
                        this.jTextFieldCidade.getText().length()),
                this.jFormattedTextFieldCEP.getText());
        String typeEmployee = (String) this.jComboBoxTipo.getSelectedItem();
        String CPF = this.jTextFieldCPF.getText();

        EmployeeEntity newEmployee = null;
        if (TypeEmployEnum.Commissionaed.getType().equals(typeEmployee)) {

            newEmployee = new CommissionedEntity(
                    this.jFormattedTextFieldComissao.getText(),
                    this.jFormattedTextFieldSalario.getText(),
                    this.jTextFieldName.getText(),
                    addressEmployee, CPF);
        } else if (TypeEmployEnum.Hourly.getType().equals(typeEmployee)) {
            newEmployee = new HourlyEntity(
                    this.jFormattedTextFieldHoraTrabalho.getText(),
                    this.jTextFieldName.getText(),
                    addressEmployee, CPF);
        } else if (TypeEmployEnum.Salaried.getType().equals(typeEmployee)) {
            newEmployee = new SalariedEntity(
                    this.jFormattedTextFieldSalario.getText(),
                    this.jTextFieldName.getText(),
                    addressEmployee, CPF);
        }
        return newEmployee;
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButtonClear;
    private javax.swing.JButton jButtonDelete;
    private javax.swing.JButton jButtonSalvar;
    private javax.swing.JButton jButtonUndo;
    private javax.swing.JComboBox<String> jComboBoxTipo;
    private javax.swing.JFormattedTextField jFormattedTextFieldCEP;
    private javax.swing.JFormattedTextField jFormattedTextFieldComissao;
    private javax.swing.JFormattedTextField jFormattedTextFieldHoraTrabalho;
    private javax.swing.JFormattedTextField jFormattedTextFieldSalario;
    private javax.swing.JLabel jLabelBairro;
    private javax.swing.JLabel jLabelCEP;
    private javax.swing.JLabel jLabelCPF;
    private javax.swing.JLabel jLabelCidade;
    private javax.swing.JLabel jLabelComissao;
    private javax.swing.JLabel jLabelHoraTrabalho;
    private javax.swing.JLabel jLabelLogradouro;
    private javax.swing.JLabel jLabelNome;
    private javax.swing.JLabel jLabelNumero;
    private javax.swing.JLabel jLabelSalario;
    private javax.swing.JLabel jLabelTipo;
    private javax.swing.JTextField jTextFieldBairro;
    private javax.swing.JTextField jTextFieldCPF;
    private javax.swing.JTextField jTextFieldCidade;
    private javax.swing.JTextField jTextFieldLogradouro;
    private javax.swing.JTextField jTextFieldName;
    private javax.swing.JTextField jTextFieldNumero;
    // End of variables declaration//GEN-END:variables
}
